sudo: require
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - cmake
            - libsdl2-dev
      env:
        - CC=gcc-6 CXX=g++-6 BOOST_VER=1.64.0

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake
            - libsdl2-dev
            - llvm
      env:
        - CC=clang-4.0 CXX=clang++-4.0 BOOST_VER=1.64.0

install:
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
  - tar xf lcov_1.13.orig.tar.gz
  - sudo make -C lcov-1.13/ install
  - sudo pip install codecov
  - wget -O "boost_$BOOST_VER.tar.gz" "http://sourceforge.net/projects/boost/files/boost/$BOOST_VER/boost_$BOOST_VER.tar.gz/download"
  - tar xzf "boost_$BOOST_VER.tar.gz"
  - cd "boost_$BOOST_VER"
  - ./bootstrap.sh --with-libraries=program_options,filesystem,system
  - sudo ./b2 link=shared threading=multi variant=release install > boost.compile.log
  - cd ..

before_script:  
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_WINDOW_ALWAYS_ON_TOP=no -DWITH_COVERAGE=yes -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..

script:
  - make mlogo_test_coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
